general {
    lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
}

listener {
    timeout = 90
    on-timeout = notify-send *feelin slweepy ~*
    on-resume = notify-send *yawn*
}

listener {
    timeout = 120
	on-timeout = hyprctl dispatch 'hl.dsp.dpms("off")'
	on-resume = hyprctl dispatch 'hl.dsp.dpms("on")'
}

listener {
    timeout = 300
	on-timeout = ~/.config/hypr/utils/lock-with-manager.sh
}
